/*
 * Visier Document Search API
 * Visier API for searching for Visier documents
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DocumentSearchLinkDTO
 */
public class DocumentSearchLinkDTOTest {
    private final DocumentSearchLinkDTO model = new DocumentSearchLinkDTO();

    /**
     * Model tests for DocumentSearchLinkDTO
     */
    @Test
    public void testDocumentSearchLinkDTO() {
        // TODO: test DocumentSearchLinkDTO
    }

    /**
     * Test the property 'href'
     */
    @Test
    public void hrefTest() {
        // TODO: test href
    }

    /**
     * Test the property 'verb'
     */
    @Test
    public void verbTest() {
        // TODO: test verb
    }

}
