/*
 * Visier Document Search API
 * Visier API for searching for Visier documents
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.DocumentSearchLinkDTO;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SimpleDocumentHeaderSearchResultDTO
 */
public class SimpleDocumentHeaderSearchResultDTOTest {
    private final SimpleDocumentHeaderSearchResultDTO model = new SimpleDocumentHeaderSearchResultDTO();

    /**
     * Model tests for SimpleDocumentHeaderSearchResultDTO
     */
    @Test
    public void testSimpleDocumentHeaderSearchResultDTO() {
        // TODO: test SimpleDocumentHeaderSearchResultDTO
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

    /**
     * Test the property 'relevance'
     */
    @Test
    public void relevanceTest() {
        // TODO: test relevance
    }

    /**
     * Test the property 'viewLink'
     */
    @Test
    public void viewLinkTest() {
        // TODO: test viewLink
    }

}
