/*
 * Visier Document Search API
 * Visier API for searching for Visier documents
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.DocumentSearchLinkDTO;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * Structure of a single document header search using the Simple search operation.
 */
@ApiModel(description = "Structure of a single document header search using the Simple search operation.")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class SimpleDocumentHeaderSearchResultDTO {
  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_DISPLAY_NAME = "displayName";
  @SerializedName(SERIALIZED_NAME_DISPLAY_NAME)
  private String displayName;

  public static final String SERIALIZED_NAME_RELEVANCE = "relevance";
  @SerializedName(SERIALIZED_NAME_RELEVANCE)
  private Double relevance;

  public static final String SERIALIZED_NAME_VIEW_LINK = "viewLink";
  @SerializedName(SERIALIZED_NAME_VIEW_LINK)
  private DocumentSearchLinkDTO viewLink;

  public SimpleDocumentHeaderSearchResultDTO() {
  }

  public SimpleDocumentHeaderSearchResultDTO description(String description) {
    
    
    
    
    this.description = description;
    return this;
  }

   /**
   * The &#x60;Web Template Framework&#x60; representation of the search result element. This commonly displayed alongside the result by search portals.
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The `Web Template Framework` representation of the search result element. This commonly displayed alongside the result by search portals.")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    
    
    
    this.description = description;
  }


  public SimpleDocumentHeaderSearchResultDTO displayName(String displayName) {
    
    
    
    
    this.displayName = displayName;
    return this;
  }

   /**
   * The display name of the element in the search result.
   * @return displayName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The display name of the element in the search result.")

  public String getDisplayName() {
    return displayName;
  }


  public void setDisplayName(String displayName) {
    
    
    
    this.displayName = displayName;
  }


  public SimpleDocumentHeaderSearchResultDTO relevance(Double relevance) {
    
    
    
    
    this.relevance = relevance;
    return this;
  }

   /**
   * The relevance of the search result and a number between &#x60;0&#x60; and &#x60;100&#x60;.
   * @return relevance
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The relevance of the search result and a number between `0` and `100`.")

  public Double getRelevance() {
    return relevance;
  }


  public void setRelevance(Double relevance) {
    
    
    
    this.relevance = relevance;
  }


  public SimpleDocumentHeaderSearchResultDTO viewLink(DocumentSearchLinkDTO viewLink) {
    
    
    
    
    this.viewLink = viewLink;
    return this;
  }

   /**
   * Use the &#x60;viewLink&#x60; to build a web request to view this document.
   * @return viewLink
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Use the `viewLink` to build a web request to view this document.")

  public DocumentSearchLinkDTO getViewLink() {
    return viewLink;
  }


  public void setViewLink(DocumentSearchLinkDTO viewLink) {
    
    
    
    this.viewLink = viewLink;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the SimpleDocumentHeaderSearchResultDTO instance itself
   */
  public SimpleDocumentHeaderSearchResultDTO putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SimpleDocumentHeaderSearchResultDTO simpleDocumentHeaderSearchResultDTO = (SimpleDocumentHeaderSearchResultDTO) o;
    return Objects.equals(this.description, simpleDocumentHeaderSearchResultDTO.description) &&
        Objects.equals(this.displayName, simpleDocumentHeaderSearchResultDTO.displayName) &&
        Objects.equals(this.relevance, simpleDocumentHeaderSearchResultDTO.relevance) &&
        Objects.equals(this.viewLink, simpleDocumentHeaderSearchResultDTO.viewLink)&&
        Objects.equals(this.additionalProperties, simpleDocumentHeaderSearchResultDTO.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, displayName, relevance, viewLink, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SimpleDocumentHeaderSearchResultDTO {\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    relevance: ").append(toIndentedString(relevance)).append("\n");
    sb.append("    viewLink: ").append(toIndentedString(viewLink)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("description");
    openapiFields.add("displayName");
    openapiFields.add("relevance");
    openapiFields.add("viewLink");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to SimpleDocumentHeaderSearchResultDTO
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!SimpleDocumentHeaderSearchResultDTO.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SimpleDocumentHeaderSearchResultDTO is not found in the empty JSON string", SimpleDocumentHeaderSearchResultDTO.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      if ((jsonObj.get("displayName") != null && !jsonObj.get("displayName").isJsonNull()) && !jsonObj.get("displayName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `displayName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("displayName").toString()));
      }
      // validate the optional field `viewLink`
      if (jsonObj.get("viewLink") != null && !jsonObj.get("viewLink").isJsonNull()) {
        DocumentSearchLinkDTO.validateJsonObject(jsonObj.getAsJsonObject("viewLink"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SimpleDocumentHeaderSearchResultDTO.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SimpleDocumentHeaderSearchResultDTO' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SimpleDocumentHeaderSearchResultDTO> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SimpleDocumentHeaderSearchResultDTO.class));

       return (TypeAdapter<T>) new TypeAdapter<SimpleDocumentHeaderSearchResultDTO>() {
           @Override
           public void write(JsonWriter out, SimpleDocumentHeaderSearchResultDTO value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public SimpleDocumentHeaderSearchResultDTO read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             SimpleDocumentHeaderSearchResultDTO instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of SimpleDocumentHeaderSearchResultDTO given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of SimpleDocumentHeaderSearchResultDTO
  * @throws IOException if the JSON string is invalid with respect to SimpleDocumentHeaderSearchResultDTO
  */
  public static SimpleDocumentHeaderSearchResultDTO fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SimpleDocumentHeaderSearchResultDTO.class);
  }

 /**
  * Convert an instance of SimpleDocumentHeaderSearchResultDTO to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

