openapi: 3.0.3
info:
  description: Visier API for searching for Visier documents
  license:
    name: "Apache License, Version 2.0"
    url: https://www.apache.org/licenses/LICENSE-2.0
  title: Visier Document Search API
  version: 22222222.99201.1200
  x-api-status-urls: false
  x-konfig-has-globally-required-security: true
servers:
- url: "https://{vanity-name}.api.visier.io"
  variables:
    vanity-name:
      default: vanity
security:
- ApiKeyAuth: []
  BearerAuth: []
- ApiKeyAuth: []
  CookieAuth: []
- ApiKeyAuth: []
  OAuth2Auth: []
tags:
- name: DocumentSearch
paths:
  /v1alpha/search/simple/document-headers:
    get:
      description: |-
        Perform a simple search for Visier document headers, such as analysis titles. Simple search doesn't support keywords, Boolean expressions, or any other advanced search features.
         Example: `GET /v1alpha/search/simple/document-headers?q=My+Query&limit=10` returns the first 10 document headers that best match the query string `My Query`.

         <br>**Note:** <em>This API is in **alpha**. While in alpha, APIs may change in a breaking way without notice; functionality may be removed, and no deprecation notices will be issued.
         If you are interested in using this API, please contact your Customer Success Manager (CSM).</em>
      operationId: DocumentSearch_SimpleSearchDocumentHeaders
      parameters:
      - description: The search query string.
        explode: true
        in: query
        name: q
        required: false
        schema:
          type: string
        style: form
      - description: The maximum number of results to return. Defaults to 100.
        explode: true
        in: query
        name: limit
        required: false
        schema:
          format: int32
          type: integer
        style: form
      - description: "The index to start retrieving results from, also known as offset.\
          \ Defaults to 0."
        explode: true
        in: query
        name: offset
        required: false
        schema:
          format: int32
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleDocumentHeaderSearchResponseDTO'
          description: OK
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
          description: Default error response
      summary: Perform a simple search for Visier document headers
      tags:
      - DocumentSearch
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--v1alpha-search-simple-document-headers
      x-accepts: application/json
components:
  schemas:
    DocumentSearchLinkDTO:
      description: Defines the attributes of a web request to reference documents
        in the search results.
      example:
        verb: verb
        href: href
      properties:
        href:
          description: The URL pointing to the specific document.
          type: string
        verb:
          description: The verb to use when formulating the web request. This is commonly
            `GET`.
          type: string
      type: object
    GoogleProtobufAny:
      additionalProperties: true
      description: Contains an arbitrary serialized message along with a @type that
        describes the type of the serialized message.
      properties:
        '@type':
          description: The type of the serialized message.
          type: string
      type: object
    SimpleDocumentHeaderSearchResponseDTO:
      description: The response body structure for Simple document header search operations.
      example:
        documentHeaders:
        - displayName: displayName
          description: description
          viewLink:
            verb: verb
            href: href
          relevance: 0.8008281904610115
        - displayName: displayName
          description: description
          viewLink:
            verb: verb
            href: href
          relevance: 0.8008281904610115
      properties:
        documentHeaders:
          description: The ordered collection of document header search results. The
            results are sorted according to their relevance in a descending order.
          items:
            $ref: '#/components/schemas/SimpleDocumentHeaderSearchResultDTO'
          type: array
      type: object
      x-konfig-is-used-in-successful-response: true
    SimpleDocumentHeaderSearchResultDTO:
      description: Structure of a single document header search using the Simple search
        operation.
      example:
        displayName: displayName
        description: description
        viewLink:
          verb: verb
          href: href
        relevance: 0.8008281904610115
      properties:
        description:
          description: The `Web Template Framework` representation of the search result
            element. This commonly displayed alongside the result by search portals.
          type: string
        displayName:
          description: The display name of the element in the search result.
          type: string
        relevance:
          description: The relevance of the search result and a number between `0`
            and `100`.
          format: double
          type: number
        viewLink:
          $ref: '#/components/schemas/DocumentSearchLinkDTO'
      type: object
      x-konfig-properties:
        viewLink:
          description: Use the `viewLink` to build a web request to view this document.
    Status:
      description: The response structure for errors.
      properties:
        errorCode:
          description: Error classification.
          type: string
        message:
          description: Error message describing the root cause of the error.
          type: string
      type: object
      x-konfig-is-used-in-successful-response: true
    konfig-generated-schema-single-parameter-schema-get--v1alpha-search-simple-document-headers:
      properties:
        q:
          type: string
        limit:
          format: int32
          type: integer
        offset:
          format: int32
          type: integer
      type: object
      x-do-not-generate: true
      x-konfig-is-parameter:
      - q
      - limit
      - offset
  securitySchemes:
    CookieAuth:
      in: cookie
      name: VisierASIDToken
      type: apiKey
      x-konfig-globally-required-security: false
    ApiKeyAuth:
      in: header
      name: apikey
      type: apiKey
      x-konfig-globally-required-security: true
    BearerAuth:
      scheme: bearer
      type: http
      x-konfig-globally-required-security: false
    OAuth2Auth:
      flows:
        authorizationCode:
          authorizationUrl: /v1/auth/oauth2/authorize
          scopes:
            read: Grants read access
            write: Grants write access
          tokenUrl: /v1/auth/oauth2/token
        password:
          scopes:
            read: Grants read access
            write: Grants write access
          tokenUrl: /v1/auth/oauth2/token
      type: oauth2
      x-konfig-globally-required-security: false

